package net.tuna.playlist;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabase;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class JdbcPlaylistRepositoryTest{

    @Autowired
    JdbcTemplate jdbcTemplate;

    EmbeddedDatabase database;

    PlaylistRepository playlistRepository;

    @BeforeEach
    void setup() {
        database = new EmbeddedDatabaseBuilder()
                .generateUniqueName(true)
                .setType(EmbeddedDatabaseType.H2)
                .build();

        jdbcTemplate = new JdbcTemplate(database);
        playlistRepository = new JdbcPlaylistRepository(jdbcTemplate);

        jdbcTemplate.execute("DROP TABLE IF EXISTS playlists");
        jdbcTemplate.execute("DROP TABLE IF EXISTS members");

        jdbcTemplate.execute("""
            CREATE TABLE members (
                id BIGINT PRIMARY KEY
            )
        """);

        jdbcTemplate.execute("""
                CREATE TABLE playlists (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    member_id BIGINT NOT NULL,
                    name VARCHAR(255) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        
                    CONSTRAINT fk_playlists_member
                        FOREIGN KEY(member_id)
                        REFERENCES members(id)
                        ON DELETE CASCADE,
        
                    CONSTRAINT uk_playlists_member_name
                        UNIQUE (member_id, name)
                )
        """);

        jdbcTemplate.update("""
            INSERT INTO members (id)
            VALUES (1), (2)
        """
        );
    }

    @AfterEach
    void cleanup() {
        database.shutdown();
    }

    @Test
    void 플레이리스트_생성() {
        // given
        long memberId = 1;

        Playlist playlist = new Playlist();

        playlist.setName("test_playlist");
        playlist.setMemberId(memberId);

        //when
        playlistRepository.save(playlist);

        // then
        Integer count = jdbcTemplate.queryForObject("""
            SELECT COUNT(*)
            FROM playlists
            WHERE name = ?
                AND member_id = ?
        """, Integer.class,
                "test_playlist",
                memberId
        );

        assertEquals(1, count.intValue());
    }
}
